spring:
  mvc:
    problemdetails:
      enabled: false
  application:
    name: PayFlash
  datasource:
    url: jdbc:postgresql://localhost:5432/flashpay
    username: postgres
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt-secret: flashpay-secret-key-must-be-long-enough-256-bits
    jwt-expiration: 86400000